### ISSUE TITLE
read

### ISSUE THREAD

**Issue by mozdevcontrib** [Jiab77/libvirt-web#1]
Lost phone. Email me. Have something. Delete after reading.

- intr0

Edit: GMAIL I shall not mail. `mailto:admin@iosprivacy.com` mail me you may if only not from the government giveaway. Google it be google I say if God I believed I'd see Google (and Microsoft, Apple, Yahoo, AOL, Yandex, etc etc etc I repeat, why of course 'tis be since I make believe that thing called God and watch it lay all of the above fore mentioned Multinationals dead, dead, dead. And to think that I saw it on Mulberry Street.

**Comment by Jiab77** [comment]
Hi bro,

What is your issue? I haven't finished this project yet but I'm still
working on it.

Just let me know and I'd be pleased to debug your issue.

Thanks for using one of my projects. That's really appreciated!

++

Jonathan

**Comment by mozdevcontrib** [comment]
No issue. It's Christmas in 5 days and I have a gift for you, some dude in Switzerland. Why? Because no one I know in rl would appreciate it.

~intr0 Ⓐ Sent from ProtonMail Professional

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mozdevcontrib** [comment]
Get some PGP keys on keybase and I'll boot up my workstation so I can gift this. Hurry before I change my mind. ⏳ Or if you must just email me with God's mini ass is licked (by the c 👁 🅰️, that is...) Peace bro. Closing this.

**Comment by Jiab77** [comment]
Can't do much right now, I'm in the train...
