### ISSUE TITLE
Can not run the web interface by the PHP Embedded Web Server

### ISSUE THREAD

**Issue by doushang** [Jiab77/libvirt-web#2]
Hello,
When I  run the web interface by the PHP Embedded Web Server，the screen display that：
dou@dou-virtual-machine:~/libvirt-web$ php -S localhost:8001 libvirt-web.php
PHP 7.2.24-0ubuntu0.18.04.1 Development Server started at Thu Jan  2 18:10:07 2020
Listening on http://localhost:8001
Document root is /home/dou/libvirt-web
Press Ctrl-C to quit.
[Thu Jan  2 18:10:15 2020] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Thu Jan  2 18:10:15 2020] PHP Fatal error:  Unknown: Failed opening required 'libvirt-web.php' (include_path='.:/usr/share/php') in Unknown on line 0

I don't know what's wrong with it.   I have tried change directory‘s permission, but that have no effect.

**Comment by Jiab77** [comment]
Hello @doushang, thanks for using my project! :bowing_man: 
I have few changes on my side that I haven't pushed yet so I'll push them today and will also run the project with the same PHP version you're using.
I'll coming back to you once the new code is pushed and available.

**Comment by Jiab77** [comment]
Hello @doushang, I've updated the project so you should run `git pull` to get the latest code.

I've also fixed the `README`, the given running instruction was wrong. Thanks a lot for pointing me on it! :+1: 

You have to use **libvirtweb.php** instead of _**libvirt-web.php**_ so the command line become:
```
php -S localhost:8001 libvirtweb.php
```

**Comment by doushang** [comment]
Thank you so much for solving this problem, This project is cool!

**Comment by Jiab77** [comment]
> Thank you so much for solving this problem, This project is cool!

Thank you so much for your support! I'll keep updating the project with much more features. If you have any suggestions, feel free to create another issue :wink:
